// scripts/gen-keybindings-table.ts
//
// Emits docs/user/_keybindings-table.md from the source-of-truth
// keybinding registry. Run via `tsx scripts/gen-keybindings-table.ts`
// (chained from `pnpm docs:dev` and `pnpm docs:build`).

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { keybindings, type KeybindingCategory } from '../src/interaction/keybindings'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../docs/user/_keybindings-table.md')

const CATEGORY_TITLES: Record<KeybindingCategory, string> = {
  tool: 'Tools',
  operation: 'Operations',
  contextual: 'Contextual',
  navigation: 'Navigation',
}

const CATEGORY_ORDER: readonly KeybindingCategory[] = [
  'tool',
  'operation',
  'contextual',
  'navigation',
]

const escape = (s: string): string => s.replace(/\|/g, '\\|')

const renderTable = (cat: KeybindingCategory): string => {
  const rows = keybindings.filter((k) => k.category === cat)
  if (rows.length === 0) return ''
  const lines: string[] = []
  lines.push(`### ${CATEGORY_TITLES[cat]}\n`)
  lines.push('| Action | Keys | When |')
  lines.push('|---|---|---|')
  for (const k of rows) {
    const action = escape(k.id)
    const keys = k.keys.map((key) => `\`${escape(key)}\``).join(' / ')
    lines.push(`| ${action} | ${keys} | ${k.when} |`)
  }
  lines.push('')
  return lines.join('\n')
}

const body = [
  '<!-- Generated by scripts/gen-keybindings-table.ts. Do not edit by hand. -->',
  '',
  ...CATEGORY_ORDER.map(renderTable).filter(Boolean),
].join('\n')

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, body, 'utf8')
console.log(`[gen-keybindings-table] wrote ${OUT}`)
